### ISSUE TITLE
Add flag for errors backtraces

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-plus#178]
The contracts in cosmwasm repo have:

```toml
[features]
backtraces = ["cosmwasm-std/backtraces", "cosmwasm-vm/backtraces"]
```

With `cargo +nightly test --features backtraces` we can get full backtraces on any any unexpected error that shows up in our unit tests. Let's expose this in these contracts too.
